/*!
 * Nhac Web Karaoke code for JW7 v1.0.6 support & fixbug BigData
 * Copyright 2015-2018 Nhac.vn, Vega Corp
 * Dev by Tan Vu ™
 * http://nhac.vn - 2018-10-24
 */
function GoPerformance(c,b,X){function R(){b.performance&&"undefined"!==typeof L&&"function"===typeof L&&(e=new Date,"playing"==c.getState()?(u+=(e-g)/1E3,k.playing=Math.round(u),0==p&&(h.play=++p),0==v&&0<w&&(h.pause=++v)):"paused"==c.getState()?(w+=(e-g)/1E3,k.pause=Math.round(w),0==v&&(h.pause=++v),0==p&&0<u&&(h.play=++p)):"buffering"==c.getState()&&(x+=(e-g)/1E3,k.buffer=Math.round(x),0==p&&(h.play=p)),e=new Date,l[f]+=Math.round((e-r)/1E3),r=new Date,L(),S())}function S(){g=new Date;w=u=x=0;
k={error:0,idle:0,buffer:0,playing:0,pause:0};M=N=O=p=v=P=0;h={seek:0,pause:0,play:0,user_change_profile:0,auto_change_profile:0,change_caption:0};for(var a in l)l[a]=0}function W(){A||(T=1);for(var a in U){var b=U[a];if(b.r.test(q)){y=b.s;break}}/Windows/.test(y)&&(m=/Windows (.*)/.exec(y)[1],y="Windows");switch(y){case "Mac OS X":m=/Mac OS X (10[\._\d]+)/.exec(q)[1];break;case "Android":m=/Android ([\._\d]+)/.exec(q)[1];break;case "iOS":m=/OS (\d+)_(\d+)_?(\d+)?/.exec(nVer),m=m[1]+"."+m[2]+"."+
(m[3]|0)}a=q.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i)||[];if(/trident/i.test(a[1])){var c=/\brv[ :]+(\d+)/g.exec(q)||[];return"IE "+(c[1]||"")}if("Chrome"===a[1]&&(c=q.match(/\b(OPR|Edge)\/(\d+)/),null!=c))return c.slice(1).join(" ").replace("OPR","Opera");a=a[2]?[a[1],a[2]]:[navigator.appName,navigator.appVersion,"-?"];null!=(c=q.match(/version\/(\d+)/i))&&a.splice(1,1,c[1]);H=a[0].toLowerCase();V=a[1]}function L(){b.perform_debug&&console.log("Performance::",b,H,typeof c.duration,
typeof c.getDuration,c.getDuration());if(void 0==H||0>I)"function"===typeof c.duration&&0<c.duration()?I=Math.round(c.duration()):"function"===typeof c.getDuration&&0<c.getDuration()&&(I=Math.round(c.getDuration())),W();Number.prototype.padLeft=function(a,b){var c=String(a||10).length-String(this).length+1;return 0<c?Array(c).join(b||"0")+this:this};var a=new Date,f=[a.getFullYear(),(a.getMonth()+1).padLeft(),a.getDate().padLeft()].join("-")+" "+[a.getHours().padLeft(),a.getMinutes().padLeft(),a.getSeconds().padLeft()].join(":");
a=Math.round(a.getTime()/1E3);var e=-1;"function"===typeof c.currentTime?e=Math.round(c.currentTime()):"function"===typeof c.getPosition&&(e=Math.round(c.getPosition()));d.ctime=a;d.du=J;d.uid=b.user_id;d.vid=b.vega_id;d.msi=b.msisdn;d.pid=b.package_id;d.cid=b.content_id;d.aid=b.album_id;d.ctype=b.content_type;d.uso=b.utm_source;d.ume=b.utm_medium;d.ute=b.utm_term;d.uco=b.utm_content;d.uca=b.utm_campaign;d.em=T;d.pst=k;d.event=h;d.pro=l;d.pos=e;d.dti=I;d.os=y.toLowerCase();d.osv=m;d.br=H;d.brv=V;
d.did=b.device_id;d.c=b.channel;d.s=b.session_id;d.ua=q;d.url=B;d.ref=b.url_referer;d.act=b.action_type;d.ptype=b.player_type;d.sid=b.service_id;d.sr=n;d.lst="online";d.o=b.other_info;d.etime=b.expired_time;d.cstr=f;d.v=b.version;f=btoa(JSON.stringify(d));b.perform_debug&&(console.log("player_states:::",k),console.log("events::::::::::",h),console.log("profiles_time:::",l),console.log("datas:::::::::::",d));f="https://collect.ovp.vn/nhac_collect?data="+f;window.jQuery?$.get(f,function(a,b){}):(a=
new XMLHttpRequest,a.open("GET",f,!1),a.send(null))}var B,z,C,A=!1,D="",n,E=!1,F=!1,U=[{s:"Windows 10",r:/(Windows 10.0|Windows NT 10.0)/},{s:"Windows 8.1",r:/(Windows 8.1|Windows NT 6.3)/},{s:"Windows 8",r:/(Windows 8|Windows NT 6.2)/},{s:"Windows 7",r:/(Windows 7|Windows NT 6.1)/},{s:"Windows Vista",r:/Windows NT 6.0/},{s:"Windows Server 2003",r:/Windows NT 5.2/},{s:"Windows XP",r:/(Windows NT 5.1|Windows XP)/},{s:"Windows 2000",r:/(Windows NT 5.0|Windows 2000)/},{s:"Windows ME",r:/(Win 9x 4.90|Windows ME)/},
{s:"Windows 98",r:/(Windows 98|Win98)/},{s:"Windows 95",r:/(Windows 95|Win95|Windows_95)/},{s:"Windows NT 4.0",r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{s:"Windows CE",r:/Windows CE/},{s:"Windows 3.11",r:/Win16/},{s:"Android",r:/Android/},{s:"Open BSD",r:/OpenBSD/},{s:"Sun OS",r:/SunOS/},{s:"Linux",r:/(Linux|X11)/},{s:"iOS",r:/(iPhone|iPad|iPod)/},{s:"Mac OS X",r:/Mac OS X/},{s:"Mac OS",r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{s:"QNX",r:/QNX/},{s:"UNIX",r:/UNIX/},{s:"BeOS",r:/BeOS/},{s:"OS/2",
r:/OS\/2/},{s:"Search Bot",r:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}],T=0,I=-1,q=navigator.userAgent,y="unknown",m="unknown",H,V,d={},G=0,Q=!1,K=!1,t,J=60,k={},h={},l={},x=0,u=0,w=0,r,g=new Date,e,P=0,v=0,p=0,O=0,N=0,M=0,f;c.onReady(function(a){b.perform_debug&&console.log("onReady::::::::",b,c.getConfig());k.error=0;0<b.duration&&(J=b.duration);t=setInterval(R,1E3*J);b.perform_debug&&console.log("CheckHost::",B,z,C,A,D);B=document.URL;z=window.location!=window.parent.location?
window.parent.location:document.location;"undefined"==z&&(z=B);C=z.hostname;0<=C.indexOf("nhac.vn")?(A=!0,void 0!=b&&void 0!=b.mode&&(D=b.mode)):(A=!1,D=0<C.indexOf("?embed=1")?"iframe":"embed");b.modepro=D;b.perform_debug&&console.log("CheckHost::onsite",B,"referrer:",z,"domainReferrer:",C,"hostmode:",A,"mode:",D,"config.mode:",b.mode,"config.modepro:",b.modepro)});c.on("meta",function(a){e=new Date;b.perform_debug&&console.log("onMeta:::::::::duration",a.duration,a.type,a.width,a.height,c.getState(),
g.getTime(),e.getTime(),e-g)});c.on("firstFrame",function(a){e=new Date;b.perform_debug&&console.log("onFirstFrame:::loadTime/type",a.loadTime,a.type,c.getState(),g.getTime(),e.getTime(),e-g);x+=(e-g)/1E3;g=new Date;Q=!0});c.on("buffer",function(a){e=new Date;b.perform_debug&&console.log("onBuffer:::::::oldstate",a.oldstate,g.getTime(),e.getTime(),e-g);"idle"==a.oldstate&&(k.idle=Math.round((e-g)/1E3));g=new Date});c.on("pause",function(a){K?(K=!1,c.play(!0)):(e=new Date,b.perform_debug&&console.log("onPaused:::::::oldstate",
a.oldstate,g.getTime(),e.getTime(),e-g),"playing"==a.oldstate&&(u+=(e-g)/1E3,k.playing=Math.round(u)),g=new Date,h.pause=++v)});c.on("play",function(a){e=new Date;b.perform_debug&&console.log("onPlay:::::::::oldstate",a.oldstate,c.getState(),g.getTime(),e.getTime(),e-g);"buffering"==a.oldstate?(x+=(e-g)/1E3,k.buffer=Math.round(x)):"paused"==a.oldstate&&(w+=(e-g)/1E3,k.pause=Math.round(w));g=new Date;h.play=++p});c.on("playlistItem",function(a){b.perform_debug&&(console.log("playlistItem:::::::::source_rec player.getPlaylist()",
c.getPlaylist(),c.getPlaylist().length),console.log("playlistItem:::::::::source_rec in_complete=",E,", first_song_played=",F,n,b.source_rec));1<c.getPlaylist().length?F?E?(E=!1,n=void 0==b.source_rec||""==b.source_rec?"next":b.source_rec):n="rand":(void 0==n&&(F=!0),n=void 0==b.source_rec||""==b.source_rec?"next":b.source_rec):n=void 0==b.source_rec||""==b.source_rec?"none":b.source_rec;if(void 0===b.content_id||"album"===b.content_type)b.content_id=a.item.mediaid;void 0!=t&&Q&&(clearInterval(t),
S(),t=setInterval(R,1E3*J));b.perform_debug&&console.log("playlistItem:::::::::source_rec",n)});c.on("seek",function(a){b.perform_debug&&console.log("onSeek:::::::::evt",a,P);h.seek=++P});c.on("levels",function(a){var d=a.levels;b.perform_debug&&console.log("levels:::::::::",G,a.currentQuality,a,d);for(var e=0;e<d.length;e++){var g=d[e].label;g.toLowerCase().indexOf("k");"Auto"!=g&&(g=g.replace("p",""),g=g.replace("k",""),g=g.replace("K",""),l[g]=0)}G=a.currentQuality;if(void 0==f||0==c.getPosition())r=
new Date;f=d[a.currentQuality].label;f=f.replace("p","");f=f.replace("k","");f=f.replace("K","")});c.on("visualQuality",function(a){b.perform_debug&&console.log("visualQuality::evt",a,N);h.auto_change_profile=++N;void 0!=f&&0!=c.getPosition()&&(e=new Date,l[f]+=Math.round((e-r)/1E3));r=new Date;f=c.getQualityLevels()[a.level.index].label;f=f.replace("p","");f=f.replace("k","");f=f.replace("K","")});c.on("levelsChanged",function(a){var d=a.levels,g=d[0].label;("Auto"==g||"T\u1ef1 \u0111\u1ed9ng"==
g)&&Q&&(0<a.currentQuality&&a.currentQuality<G||0==G)&&(K=!0,c.pause(!0));b.perform_debug&&console.log("levelsChanged:::::::::evt",a,O,K,a.currentQuality,d.length);h.user_change_profile=++O;void 0!=f&&(e=new Date,l[f]+=Math.round((e-r)/1E3),r=new Date);a.currentQuality>=d.length||(f=d[a.currentQuality].label,"Auto"!=f&&(f=f.replace("p",""),f=f.replace("k",""),f=f.replace("K","")),G=a.currentQuality)});c.on("captionsChanged",function(a){b.perform_debug&&console.log("captionsChanged:::::::::evt",a,
M,c.getPosition());0<c.getPosition()&&(h.change_caption=++M)});c.on("complete",function(a){F=E=!0;b.perform_debug&&(console.log("complete",typeof nextUp,t,b.content_type),console.log("complete:::::::::source_rec",E,F,n,b.source_rec));void 0!=t&&clearInterval(t)});this.resize=function(a,b){}};